src/Entity/Artist.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use App\Repository\BackOffice\ArtistBORepository;


#[ORM\Entity(repositoryClass: ArtistBORepository::class)]
class Artist 
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]    
    private ?string $artistName = null;

    #[ORM\Column(length: 50)]    
    private ?string $artistFirstname = null;

    #[ORM\Column(length: 255, unique: true, nullable: true)]
    private ?string $slug = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
     private ?\DateTimeInterface $artistBirthDate = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $artistDeathDate = null;

    #[ORM\Column(length: 100)]
    private ?string $artistJob = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $artistBio = null;

    #[ORM\Column(type: 'boolean')]
    private bool $isAnonymized = false;

    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    private ?\DateTimeImmutable $anonymizeAt = null;

    /**
     * @var Collection<int, Show>
     */
    #[ORM\OneToMany(targetEntity: Show::class, mappedBy: 'artist')]
    private Collection $shows;

    public function __construct()
    {
        $this->shows = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getArtistName(): ?string
    {
        return $this->artistName;
    }

    public function setArtistName(string $artistName): static
    {
        $this->artistName = $artistName;

        return $this;
    }

    public function getArtistFirstname(): ?string
    {
        return $this->artistFirstname;
    }

    public function setArtistFirstname(string $artistFirstname): static
    {
        $this->artistFirstname = $artistFirstname;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function createSlugArtist(): string
    {
       $slugify = new Slugify();
    
    // Construction du slug à partir de l'ID, du prénom et du nom
    $slugSource = $this->id . '-' . $this->artistFirstname . '-' . $this->artistName;
    
    return $slugify->slugify($slugSource);
    }

    public function getArtistBirthDate(): ?\DateTimeInterface
    {
        return $this->artistBirthDate;
    }

    public function setArtistBirthDate(?\DateTimeInterface $artistBirthDate): static
    {
        $this->artistBirthDate = $artistBirthDate;

        return $this;
    }

    public function getArtistBirthDateFr()
    {
        $date = $this->artistBirthDate;

        // Format date FR
        $dateFormat = new \IntlDateFormatter(
                    'fr_FR', //Pays
                    \IntlDateFormatter::LONG, //Format long
                    \IntlDateFormatter::NONE); //Fuseau horaire ou heure

        return $dateFormat->format($date);  
         
    }

    public function getArtistDeathDate(): ?\DateTimeInterface
    {
        return $this->artistDeathDate;
    }

    public function setArtistDeathDate(?\DateTimeInterface $artistDeathDate): static
    {
        $this->artistDeathDate = $artistDeathDate;

        return $this;
    }

    public function getArtistDeathDateFr()
    {
        $date = $this->artistDeathDate;

        // Format date FR
        $dateFormat = new \IntlDateFormatter(
                    'fr_FR', //Pays
                    \IntlDateFormatter::LONG, //Format long
                    \IntlDateFormatter::NONE); //Fuseau horaire ou heure

        return $dateFormat->format($date);         
    }   

    public function getArtistJob(): ?string
    {
        return $this->artistJob;
    }

    public function setArtistJob(string $artistJob): static
    {
        $this->artistJob = $artistJob;

        return $this;
    }

    public function getArtistBio(): ?string
    {
        return $this->artistBio;
    }

    public function setArtistBio(?string $artistBio): static  
    {
        $this->artistBio = $artistBio;

        return $this;
    }

    //Gestion des artistes anonymisés
    public function isIsAnonymized(): ?bool
    {
        return $this->isAnonymized;
    }

    public function setIsAnonymized(bool $isAnonymized): static
    {
        $this->isAnonymized = $isAnonymized;

        return $this;
    }

    //Gestion des artistes anonymisés après leur prochaine expo
    public function getAnonymizeAt(): ?\DateTimeImmutable
    {
        return $this->anonymizeAt;
    }

    public function setAnonymizeAt(?\DateTimeImmutable $anonymizeAt): self
    {
        $this->anonymizeAt = $anonymizeAt;

        return $this;
    }

    /**
     * @return Collection<int, Show>
     */
    public function getShows(): Collection
    {
        return $this->shows;
    }

    public function addShow(Show $show): static
    {
        if (!$this->shows->contains($show)) {
            $this->shows->add($show);
            $show->setArtist($this);
        }

        return $this;
    }

    public function removeShow(Show $show): static
    {
        if ($this->shows->removeElement($show)) {
            // set the owning side to null (unless already changed)
            if ($show->getArtist() === $this) {
                $show->setArtist(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->artistFirstname. ' ' .$this->artistName;
    }
}

src/Entity/Exhibition.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use App\Repository\Share\ExhibitionShareRepository;

#[ORM\Entity(repositoryClass: ExhibitionShareRepository::class)]
class Exhibition
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titleExhibit = null;

    #[ORM\Column(length: 255, unique: true, nullable: true)]
   private ?string $slug = null; // Propriété slug

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $mainImage = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $dateWarBegin = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $dateWarEnd = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    private ?\DateTimeImmutable $dateExhibit = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $hourBegin = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $hourEnd = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $descriptionExhibit = null;

    /**
     * @var Collection<int, OrderDetail>
     */
    #[ORM\OneToMany(targetEntity: OrderDetail::class, mappedBy: 'exhibition')]
    private Collection $orderDetail;

    /**
     * @var Collection<int, Show>
     */
    #[ORM\OneToMany(targetEntity: Show::class, mappedBy: 'exhibition')]
    private Collection $shows;

    #[ORM\ManyToOne(inversedBy: 'exhibitions')]
    private ?User $user = null;
    

    #[ORM\Column(length: 255)]
    private ?string $mainImageAlt = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $hookExhibit = null;

    #[ORM\Column(length: 255)]
    private ?string $subtitleExhibit = null;

    /**
     * @var Collection<int, TicketPricing>
     */
    #[ORM\OneToMany(targetEntity: TicketPricing::class, mappedBy: 'exhibition')]
    private Collection $ticketPricings;

    #[ORM\Column]
    private ?int $stockMax = null;

    #[ORM\Column]
   private ?int $stockAlert = null;

    public function __construct()
    {
        $this->orderDetail = new ArrayCollection();
        $this->shows = new ArrayCollection();
        $this->ticketPricings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMainImage(): ?string
    {
        return $this->mainImage;
    }

    public function setMainImage(?string $mainImage): static
    {
        $this->mainImage = $mainImage;

        return $this;
    }

    public function getMainImageAlt(): ?string
    {
        return $this->mainImageAlt;
    }

    public function setMainImageAlt(string $mainImageAlt): static
    {
        $this->mainImageAlt = $mainImageAlt;

        return $this;
    }

    public function getTitleExhibit(): ?string
    {
        return $this->titleExhibit;
    }

    public function setTitleExhibit(string $titleExhibit): static
    {
        $this->titleExhibit = $titleExhibit;

        return $this;
    }

    public function getSlug(): ?string 
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): static 
    {
        $this->slug = $slug;
        return $this;
    }

    public function createSlugDateTitleExhibit(): string
    {
        $slugify = new Slugify();
        $datePart = $this->dateExhibit ? $this->dateExhibit->format('dmY') : '';
        $namePart = $this->titleExhibit;

        $slugSource = $datePart . '-' . $namePart;
        return $slugify->slugify($slugSource);
    }

    public function getSubtitleExhibit(): ?string
    {
        return $this->subtitleExhibit;
    }

    public function setSubtitleExhibit(?string $subtitleExhibit): static
    {
        $this->subtitleExhibit = $subtitleExhibit;

        return $this;
    }

    public function getHookExhibit(): ?string
    {
        return $this->hookExhibit;
    }

    public function setHookExhibit(?string $hookExhibit): static
    {
        $this->hookExhibit = $hookExhibit;

        return $this;
    }
    

    public function getDateWarBegin(): ?\DateTimeInterface
    {
        return $this->dateWarBegin;
    }

    public function setDateWarBegin(\DateTimeInterface $dateWarBegin): static
    {
        $this->dateWarBegin = $dateWarBegin;

        return $this;
    }

    public function getDateWarBeginFr()
    {
        return $this->dateWarBegin->format('Y');
         
    }

    public function getDateWarEnd(): ?\DateTimeInterface
    {
        return $this->dateWarEnd;
    }

    public function setDateWarEnd(?\DateTimeInterface $dateWarEnd): static
    {
        $this->dateWarEnd = $dateWarEnd;

        return $this;
    }

    public function getDateWarEndFr()
    {
        if ($this->dateWarEnd !== null) {
            return $this->dateWarEnd->format('Y');
        } else {
            return null; // Ou une autre valeur par défaut, comme une chaîne vide ""
        }
         
    }

    public function getDateExhibit(): ?\DateTimeImmutable
    {
        return $this->dateExhibit;
    }

    public function setDateExhibit(\DateTimeImmutable $dateExhibit): static
    {
        $this->dateExhibit = $dateExhibit;

        return $this;
    }

    public function getDateExhibitFr()
    {
        $date = $this->dateExhibit;

        // Create a DateTimeFormatter for French locale
        $dateFormat = new \IntlDateFormatter(
                    'fr_FR', //Pays
                    \IntlDateFormatter::LONG, //Format long
                    \IntlDateFormatter::NONE); //Fuseau horaire ou heure

        return $dateFormat->format($date);         
    }

    public function getDateExhibitFile()
    {
        $date = $this->dateExhibit;

        return $date->format('Ymd');      
    }

    public function getHourBegin(): ?\DateTimeInterface
    {
        return $this->hourBegin;
    }

    public function setHourBegin(\DateTimeInterface $hourBegin): static
    {
        $this->hourBegin = $hourBegin;

        return $this;
    }

    public function getHourBeginFr()
    {
        return $this->hourBegin->format('H\hi');
    }

    public function getHourEnd(): ?\DateTimeInterface
    {
        return $this->hourEnd;
    }

    public function setHourEnd(\DateTimeInterface $hourEnd): static
    {
        $this->hourEnd = $hourEnd;

        return $this;
    }

    public function getHourEndFr()
    {
        return $this->hourEnd->format('H\hi');
    }

    public function getDescriptionExhibit(): ?string
    {
        return $this->descriptionExhibit;
    }

    public function setDescriptionExhibit(string $descriptionExhibit): static
    {
        $this->descriptionExhibit = $descriptionExhibit;

        return $this;
    }

    /**
     * @return Collection<int, OrderDetail>
     */
    public function getOrderDetails(): Collection
    {
        return $this->orderDetail;
    }

    public function addOrderDetail(OrderDetail $orderDetail): static
    {
        if (!$this->orderDetail->contains($orderDetail)) {
            $this->orderDetail->add($orderDetail);
            $orderDetail->setExhibition($this);
        }

        return $this;
    }

    public function removeOrderDetail(OrderDetail $orderDetail): static
    {
        if ($this->orderDetail->removeElement($orderDetail)) {
            // set the owning side to null (unless already changed)
            if ($orderDetail->getExhibition() === $this) {
                $orderDetail->setExhibition(null);
            }
        }

        return $this;
    }

   
    /**
     * @return Collection<int, Show>
     */
    public function getShows(): Collection
    {
        return $this->shows;
    }

    public function addShow(Show $show): static
    {
        if (!$this->shows->contains($show)) {
            $this->shows->add($show);
            $show->setExhibition($this);
        }

        return $this;
    }

    public function removeShow(Show $show): static
    {
        if ($this->shows->removeElement($show)) {
            // set the owning side to null (unless already changed)
            if ($show->getExhibition() === $this) {
                $show->setExhibition(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, ticketPricing>
     */
    public function getTicketPricings(): Collection
    {
        return $this->ticketPricings;
    }

    public function addTicketPricing(TicketPricing $ticketPricing): static
    {
        if (!$this->ticketPricings->contains($ticketPricing)) {
            $this->ticketPricings->add($ticketPricing);
            $ticketPricing->setExhibition($this);
        }

        return $this;
    }

    public function removeTicketPricing(TicketPricing $ticketPricing): static
    {
        if ($this->ticketPricings->removeElement($ticketPricing)) {
            // set the owning side to null (unless already changed)
            if ($ticketPricing->getExhibition() === $this) {
                $ticketPricing->setExhibition(null);
            }
        }

        return $this;
    }

    public function getStockMax(): ?int
    {
        return $this->stockMax;
    }

    public function setStockMax(int $stockMax): static
    {
        $this->stockMax = $stockMax;

        return $this;
    }

    public function getStockAlert(): ?int
    {
        return $this->stockAlert;
    }

    public function setStockAlert(int $stockAlert): static
    {
        $this->stockAlert = $stockAlert;

        return $this;
    }

    //Nb de tickets réservés
    public function getTicketsReserved(): int
    {
        $totalTickets = 0;

src/Controller/ExhibitionController.php
<?php

namespace App\Controller;


use App\Entity\Exhibition;
use App\Service\CartService;
use App\Repository\TicketRepository;
use App\Repository\TicketPricingRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bridge\Doctrine\Attribute\MapEntity;
use App\Repository\Share\ExhibitionShareRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

final class ExhibitionController extends AbstractController
{
    /*Affiche la fiche complète de l'expo*/
    #[Route('/exhibition/{slug}', name: 'exhibition')]
    public function index(
        #[MapEntity(mapping: ['slug' => 'slug'])] ?Exhibition $exhibition = null,
        CartService $cartService, 
        TicketPricingRepository $ticketPricingRepository,): Response 
    {       
        // Récupérer le panier depuis la session
        $cart = $cartService->getCart();   

        // Récupérer les prix des tickets pour cette exposition spécifique
        $ticketPricings = $ticketPricingRepository->findBy(['exhibition' => $exhibition]);

        
        return $this->render('/exhibition/index.html.twig', [
            'ticketPricings' => $ticketPricings,
            'exhibition' => $exhibition,
            'cart' => $cart, 
        ]);
    }

    #[Route('/liste-des-expositions', name: 'listExhibitions')]
    public function listExhibit(        
        ExhibitionShareRepository $exhibitShareRepo): Response
    {
        //Récup uniquement les infos des prochaines expos
        $exhibitions = $exhibitShareRepo->findAllNextExhibition();


        return $this->render('exhibition/listExhibitions.html.twig', [            
            'exhibitions' => $exhibitions,        
        ]);
    }
}

 

templates/exhibition/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ exhibition.titleExhibit}}{% endblock %}

{% block description %}
Plongez dans l'univers de l'exposition "{{ exhibition.titleExhibit }}" ! Découvrez des œuvres d'art poignantes et commandez vos tickets dès maintenant pour une expérience unique.
{% endblock %}

{% block body %}
<!-- ExhibitionController CartController -->

    <h1>Exposition : <span class="longTitle pageExhibitTitle">{{ exhibition.titleExhibit}}  
        <span class="longTitle dateExhibitTitle">
            ({{ exhibition.dateWarBeginFr }} 
                {% if exhibition.dateWarEndFr is not null %}    
                        - {{ exhibition.dateWarEndFr }}
                    {% else %} à aujourd'hui
                {% endif %})
        </span>
    </span></h1>

    <section class="sectionExhibit">    
        
        <div class="dateHourPageExhibit">
            <p>{{ exhibition.dateExhibitFr }}</p>
            <p>{{ exhibition.hourBeginFr }} - {{ exhibition.hourEndFr }}</p>
        </div>

        <div class="blockImgExhibit">
            <div class="imgExhibitContainer">
                
                <img class="expoImg" src="{{ exhibition.mainImage }}" alt="{{ exhibition.mainImageAlt }}">

                {% if exhibition.ticketsRemaining <= 10 and exhibition.ticketsRemaining > 0 %}
                    <img class="imgStockExhibit" src="{{ asset('images/stocks/soon_out_of_stock.png') }}" alt="Presque épuisé">
                {% elseif exhibition.ticketsRemaining <= 10 %}
                    <img class="imgStockExhibit" src="{{ asset('images/stocks/out_of_stock.png') }}" alt="Epuisé">
                {% endif %}
            </div>

            <div class="blockTextPriceExhibit">
                <p>{{ exhibition.descriptionExhibit }}</p>
                {# ----------- #}


                {% if exhibition.ticketsRemaining > 0 %}
                    <div class="ticketsContainer">
                        <h2 class="ticketH2">Tickets :</h2>

                        <div class="ticketsExhibitContainer">
                            <div class="blockTicketExhibit">
                                {% if ticketPricings is not empty %}
                                
                                    {% for pricing in ticketPricings %}
                                        <div class="ticketExhibit">
                                            <p class="titleTicket">{{ pricing.ticket.titleTicket }}</p>                    
                                            
                                            <div class="blockTitleQtyTicket">
                                                <div class="blockPriceTicket">
                                                    {% if pricing.standardPrice > 0 %}
                                                        <p class="price">{{ pricing.standardPrice }} €</p>
                                                    {% else %}
                                                        <p class="price">Gratuit</p>
                                                    {% endif %}
                                                </div>

                                                <div class="blockQtyTicket">

                                                    <a href="{{ path('removeTicketFromCart', {'exhibitionId': exhibition.id, 'ticketId': pricing.ticket.id, 'origin': 'listExhibit'}) }}"
                                                    aria-label="{{ 'Retirer un ticket ' ~ pricing.ticket.titleTicket|lower ~ ' pour l\'exposition ' ~ exhibition.titleExhibit }}"
                                                    title="{{ 'Diminuer la quantité du ticket ' ~ pricing.ticket.titleTicket ~ ' pour l\'exposition ' ~ exhibition.titleExhibit }}">
                                                        <i class="fa-solid fa-minus"></i>
                                                    </a>

                                                    <div class="qtyProduct">  
                                                        {# Crée une clé unique pour le ticket dans le panier (id expo + id ticket) #}                              
                                                        {% set cartKey = exhibition.id ~ '_' ~ pricing.ticket.id %}
                                                        
                                                        {# Vérifie si le ticket est déjà dans le panier #}
                                                        {% if cart[cartKey] is defined %} 
                                                            <span class="nbCart">{{ cart[cartKey].qty }}</span>
                                                        {% else %}
                                                            <span class="nbCart">0</span>
                                                        {% endif %}
                                                    </div> 

                                                    <a href="{{ path('addTicketToCart', {'exhibitionId': exhibition.id, 'ticketId': pricing.ticket.id, 'origin': 'listExhibit'}) }}"
                                                    aria-label="{{ 'Ajouter un ticket ' ~ pricing.ticket.titleTicket|lower ~ ' pour l\'exposition ' ~ exhibition.titleExhibit }}"
                                                    title="{{ 'Augmenter la quantité du ticket ' ~ pricing.ticket.titleTicket ~ ' pour l\'exposition ' ~ exhibition.titleExhibit }}">
                                                        <i class="fa-solid fa-plus"></i>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}  
                                {% endif %}
                            </div>          

                            <div class="buttonTicket">
                                <a href="{{ path('cart') }}" class="btnCTA">Panier</a> 
                            </div>
                        </div>
                    
                    </div>           
                {% endif %}
            </div>
        </div>
    </section>


    <section class="sectionIntroExhibit">
            <p class="cormorantGaramond"> 
                Regards de Guerre rassemble des artistes aux horizons variés, offrant, à travers un regard neuf, une exploration des conflits d'ici et d'ailleurs. 
            </p>

            <p class="cormorantGaramond">
                Chaque salle vous immerge dans leur univers unique, proposant une perspective inédite sur ces événements marquants.
            </p>
    </section>


    <section>
        <h2 class="galerieH2">Galerie des artistes</h2>

        
        
            {% for show in exhibition.shows %}
                <div class="blockArtistPageExhibit">

                    <div class="artistInfosPageExhibit">
                        <p class="cormorantGaramond">{{ show.artist.artistFirstname }} {{ show.artist.artistName }} - {{ show.artist.artistJob }}</p>
                        <p class="cormorantGaramond">({{ show.artist.artistBirthDateFr }} - {{ show.artist.artistDeathDateFr }})</p>
                    </div>

                    <div class="artistContainer loopEven-{% if loop.index is even %}even{% endif %}">
                        <div class="blockArtist loopEven-{% if loop.index is even %}even{% endif %}">
                            <img class="artistImgPageExhibit" src="{{ show.artistPhoto }}" alt="{{ show.artistPhotoAlt }}">                 
                        
                            <p class="artistTabletNone">{{ show.artist.artistBio }} </p>
                        </div>

                        <div class="blockArtistText">
                            <p class="artistDesktopNone">{{ show.artist.artistBio }} </p>
                            <p>{{ show.artistTextArt }} </p>
                        
                    
                            <p class="artistRoomPageExhibit">Salle {{ show.room.titleRoom }}</p> 
                        </div>
                    </div>
                </div>
            {% endfor %}        
        
    </section>


{% endblock %}

templates/exhibition/listExhibitions.html.twig
{% extends 'base.html.twig' %}

{% block title %}Agenda Culturel{% endblock %}

{% block description %}
    Découvrez l'ensemble des expositions et les artistes présents.
{% endblock %}

{% block body %}
    <h1>Agenda des expositions</h1>

    <section class="sectionListAgenda">

        <div class="blockListAgendaContainer">
            {% for exhibition in exhibitions %}
                <div class="blockListAgenda">
                    
                    {# <div class="imgExhibitListAgenda"> #}
                        <img  src="{{ asset(exhibition.mainImage) }}" alt="{{ exhibition.mainImageAlt }}">
                    {# </div> #}

                    <div class="exhibitListAgenda">
                        <div class="blockDateListAgenda">
                                <p><strong>{{ exhibition.dateExhibitFr }}</strong></p>
                                <p>{{ exhibition.hourBeginFr }} à {{ exhibition.hourEndFr }}</p>
                                <p>
                                    {% if exhibition.ticketsRemaining <= 10 and exhibition.ticketsRemaining > 0 %}
                                        <img class="imgSoonOutOfStock" src="{{ asset('images/stocks/soon_out_of_stock_hor.png') }}" alt="Presque épuisé">
                                    {% elseif exhibition.ticketsRemaining <= 0 %}
                                        <img class="imgOutOfStock" src="{{ asset('images/stocks/out_of_stock_hor.png') }}" alt="Épuisé">
                                    {% endif %}
                                </p>
                        </div>

                        <div class="blockTitle">
                            <p class="cgBold titleExhibitListAgenda">{{ exhibition.titleExhibit }}
                                <span class="longTitleDate">({{ exhibition.dateWarBeginFr }} 
                                    {% if exhibition.dateWarEndFr is null %}
                                        à aujourd'hui
                                    {% else %}
                                        - {{ exhibition.dateWarEndFr }}
                                    {% endif %}
                                    )
                                </span>
                            </p>
                        </div>

                        {% if exhibition.ticketsRemaining > 0 %}
                            <a class="parkinsanBrown textHover" href="{{ path('exhibition', {'slug': exhibition.slug}) }}"
                            title="{{ 'Voir la page détaillée de l\'exposition et commander des tickets'|trans }}">
                            > Tickets
                            </a>
                        {% else %}
                            <a class="parkinsanBrown textHover" href="{{ path('exhibition', {'slug': exhibition.slug}) }}"
                            title="{{ 'Voir la page détaillée de l\'exposition'|trans }}">
                            > Fiche détaillée
                            </a>
                        {% endif %}                        
                    </div>
                </div>                
            {% endfor %}
        </div>
    </section>
{% endblock %}