src/Entity/Order.php
<?php

namespace App\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\OrderRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: '`order`')]
class Order
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $orderDateCreation = null;

    #[ORM\Column(length: 50)]
    private ?string $orderStatus = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    private ?User $user = null;

    /**
     * @var Collection<int, OrderDetail>
     */
    #[ORM\OneToMany(targetEntity: OrderDetail::class, mappedBy: 'order_')]
    private Collection $orderDetail;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $customerName = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $customerFirstname = null;

    #[ORM\Column(length: 180, nullable: true)]
    private ?string $customerEmail = null;

    #[ORM\Column(type: Types::STRING, length: 20, unique: true, nullable: true)]
    private ?string $numberInvoice = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 17, scale: 2, nullable: true)]
    private ?string $orderTotal = null;

    public function __construct()
    {
        $this->orderDetail = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOrderDateCreation(): ?\DateTimeInterface
    {
        return $this->orderDateCreation;
    }

    public function setOrderDateCreation(\DateTimeInterface $orderDateCreation): static
    {
        $this->orderDateCreation = $orderDateCreation;

        return $this;
    }

    public function getOrderDateCreationFr(): ?string
    {
        return $this->orderDateCreation?->format('d-m-y');
    }

    public function getOrderStatus(): ?string
    {
        return $this->orderStatus;
    }

    public function setOrderStatus(string $orderStatus): static
    {
        $this->orderStatus = $orderStatus;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, OrderDetail>
     */
    public function getOrderDetails(): Collection
    {
        return $this->orderDetail;
    }

    public function addOrderDetail(OrderDetail $orderDetail): static
    {
        if (!$this->orderDetail->contains($orderDetail)) {
            $this->orderDetail->add($orderDetail);
            $orderDetail->setOrder($this);
        }

        return $this;
    }

    public function removeOrderDetail(OrderDetail $orderDetail): static
    {
        if ($this->orderDetail->removeElement($orderDetail)) {
            // set the owning side to null (unless already changed)
            if ($orderDetail->getOrder() === $this) {
                $orderDetail->setOrder(null);
            }
        }

        return $this;
    }


    public function getCustomerName(): ?string
    {
        return $this->customerName;
    }

    public function setCustomerName(?string $customerName): static
    {
        $this->customerName = $customerName;

        return $this;
    }

    public function getCustomerFirstname(): ?string
    {
        return $this->customerFirstname;
    }

    public function setCustomerFirstname(?string $customerFirstname): static
    {
        $this->customerFirstname = $customerFirstname;

        return $this;
    }

    public function getCustomerEmail(): ?string
    {
        return $this->customerEmail;
    }

    public function setCustomerEmail(?string $customerEmail): static
    {
        $this->customerEmail = $customerEmail;

        return $this;
    }

    public function getNumberInvoice(): ?string
    {
        return $this->numberInvoice;
    }

    public function setNumberInvoice(?string $numberInvoice): static
    {
        $this->numberInvoice = $numberInvoice;

        return $this;
    }

    public function getOrderTotal(): ?string
    {
        return $this->orderTotal;
    }

    public function setOrderTotal(?string $orderTotal): static
    {
        $this->orderTotal = $orderTotal;

        return $this;
    }

    public function __toString()
    {
        return $this->getOrderDateCreationFr() . ' - ' . $this->id;
    }
}

templates/pdf/eticketPdf.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Vos e-tickets - Commande #{{ order.id }}</title>
    <style>
        .sectionPdf {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: space-between;
        }      
        
        .headerPdf {
            width: 100%;                     
        }

        .exposition {
            page-break-before: always; /* Force chaque exposition à commencer sur une nouvelle page */
        }
    
        
        .exposition.first {
            page-break-before: avoid; /* Empêche le saut de page avant la première exposition */
        }

        .center {
            text-align: center;
        }

        .ticket {
            border: 1px solid #ccc;
            padding-left: 15px;
            margin-bottom: 10px;
        }

        .strong {
            font-weight: bold;
        }

        h1 {
            font-size: 2em; 
            text-align: center; 
        }

        .logoPdf {
            width: 100px; 
        } 
        
        .footerPdf {
            position: fixed; 
            bottom: 0;
            left: 0;
            right: 0;
            text-align: center;
            padding: 5px 0; 
            background-color: rgba(255, 160, 122, 0.15);
            font-size: 0.7em;           
        }
        
        .footerPdf p {
            margin: 0;            
        } 
    </style>
</head>
<body>
    <section class="sectionPdf">       

        
        {% for exhibitionId, exhibitionData in groupedOrderDetails %}
            <div class="exposition {% if loop.first %}first{% endif %}">
                <div class="headerPdf">
                    <img class="logoPdf" src="{{ absolute_url(asset('images/logo.webp')) }}" alt="Logo Regards de Guerre">
                    <div>
                        <h1>Vos e-tickets - Commande #{{ order.id }}</h1>
                        <p class="center">Date de commande : {{ order.orderDateCreationFr }}</p>
                    </div>  
                </div>

                <h2><span class="strong">Exposition :</span> {{ exhibitionData.exhibition.titleExhibit }}</h2>
                <p><span class="strong">Valable uniquement le :</span> {{ exhibitionData.exhibition.dateExhibit|date('d/m/Y') }}</p>
                <p><span class="strong">Ticket(s) réservé(s) au nom de : </span>{{ order.customerName }} {{ order.customerFirstname }}</p>
        
            {% for orderDetail in exhibitionData.orderDetails %}
                <div class="ticket">
                    <p class="ticketInfoPdf"><span class="strong">Ticket :</span> {{ orderDetail.ticket.titleTicket }}</p>
                    <p class="ticketInfoPdf"><span class="strong">Quantité :</span> {{ orderDetail.quantity }}</p>
                    <p class="ticketInfoPdf"><span class="strong">Prix unitaire :</span> {{ orderDetail.unitPrice }} €</p>
                </div>
            {% endfor %}
            </div>


            <div class="footerPdf">
                <p>Regards de guerre - Association loi 1901</p>
                <p>Rue de la paix - 75000 PARIS</p>
            </div>
        {% endfor %}


        <div class="footerPdf">
            <p>Regards de guerre - Association loi 1901</p>
            <p>Rue de la paix - 75000 PARIS</p>
        </div>
    </section>
</body>
</html>

templates/pdf/invoicePdf.html.twig
<!DOCTYPE html>
<html>
<head>
    {# pdf/orderPdf.html.twig #}
    <meta charset="UTF-8">
    <title>Commande # {{invoice }}</title>
    <style>
        .sectionPdf {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: space-between;
        }

        .headerPdf {
            width: 100%;                       
        }

        h1 {
            font-size: 2em; 
            text-align: center;
            padding-bottom: 20px;  
        }

        .logoPdf {
            width: 100px; 
        }       

        .invoiceTable {
            width: 100%;
            border-collapse: collapse; /*Ferme les bordures*/
            margin-bottom: 20px;
            font-family: sans-serif; 
            font-size: 0.9em; 
        }
        
        .invoiceTable th, .invoiceTable td {
            padding: 8px 12px;
            border-bottom: 1px solid #944C43; 
            text-align: left;
        }
        
        .invoiceTable th {
            background-color: #FFA07A; 
            font-weight: bold;
        }
        
        .invoiceTable tbody tr:nth-child(even) {
            background-color: rgba(255, 160, 122, 0.15); /* even : Alternance des couleurs pour la lisibilité */
        }
        
        .invoiceTable .textRight {
            text-align: right;
        }
                
        .invoiceTable tfoot tr td {
            font-weight: bold;
            border-top: 2px solid #944C43; /* Ligne supérieure plus épaisse pour le total */
            border-bottom: none;
        }
           
               
        .invoiceTable {
            border: 1px solid #944C43;
        }
        
        .invoiceTable th,
        .invoiceTable td {
            border-right: 1px solid #944C43;
        }
        
        .invoiceTable th:last-child,
        .invoiceTable td:last-child {
            border-right: none;
        }

        .footerPdf {
            position: fixed; 
            bottom: 0;
            left: 0;
            right: 0;
            text-align: center;
            padding: 5px 0; 
            background-color: rgba(255, 160, 122, 0.15);
            font-size: 0.7em;           
        }
        
        .footerPdf p {
            margin: 0;            
        }        
        
    </style>
</head>
<body>
<section class="sectionPdf">
    <div class="headerPdf">
        <img class="logoPdf" src="{{ absolute_url(asset('images/logo.webp')) }}" alt="Logo de l'association Regards de Guerre">
    
        <h1>Commande #{{ invoice }} du {{ invoice.dateInvoice|date('d/m/Y') }}</h1>
    </div>
    

    <table class="invoiceTable">
        <thead>
            <tr>
                <th>Exposition</th>
                <th>Ticket</th>
                <th>Qté</th>
                <th class="textRight">Prix Unitaire</th>
                <th class="textRight">Prix Total</th>
            </tr>
        </thead>
        <tbody>
            {% for detail in invoice.invoiceDetails %}
                <tr>
                    <td>{{ detail.exhibitionTitle }}</td>
                    <td>{{ detail.ticketTitle }}</td>
                    <td class="textRight">{{ detail.quantity }}</td>
                    <td class="textRight">{{ detail.standardPrice }} €</td>
                    <td class="textRight">{{ (detail.quantity * detail.standardPrice) }} €</td>
                </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <td colspan="4" class="textRight">Total de la commande :</td>
                <td class="textRight">{{ invoice.orderTotal }} €</td>
            </tr>
        </tfoot>
    </table>

    <div class="footerPdf">
        <p>Regards de guerre - Association loi 1901</p>
        <p>Rue de la paix - 75000 PARIS</p>
    </div>
</section>
</body>
</html>

templates/pdf/orderPdf.html.twig
<!DOCTYPE html>
<html>
<head>
    {# pdf/orderPdf.html.twig #}
    <meta charset="UTF-8">
    <title>Commande #{{ orderData.order.id }}</title>
    <style>
        .sectionPdf {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: space-between;
        }

        .headerPdf {
            width: 100%;                       
        }

        h1 {
            font-size: 2em; 
            text-align: center;
            padding-bottom: 20px;  
        }

        .logoPdf {
            width: 100px; 
        }       

        .invoiceTable {
            width: 100%;
            border-collapse: collapse; /*Ferme les bordures*/
            margin-bottom: 20px;
            font-family: sans-serif; 
            font-size: 0.9em; 
        }
        
        .invoiceTable th, .invoiceTable td {
            padding: 8px 12px;
            border-bottom: 1px solid #944C43; 
            text-align: left;
        }
        
        .invoiceTable th {
            background-color: #FFA07A; 
            font-weight: bold;
        }
        
        .invoiceTable tbody tr:nth-child(even) {
            background-color: rgba(255, 160, 122, 0.15); /* even : Alternance des couleurs pour la lisibilité */
        }
        
        .invoiceTable .textRight {
            text-align: right;
        }
                
        .invoiceTable tfoot tr td {
            font-weight: bold;
            border-top: 2px solid #944C43; /* Ligne supérieure plus épaisse pour le total */
            border-bottom: none;
        }
           
               
        .invoiceTable {
            border: 1px solid #944C43;
        }
        
        .invoiceTable th,
        .invoiceTable td {
            border-right: 1px solid #944C43;
        }
        
        .invoiceTable th:last-child,
        .invoiceTable td:last-child {
            border-right: none;
        }

        .footerPdf {
            position: fixed; 
            bottom: 0;
            left: 0;
            right: 0;
            text-align: center;
            padding: 5px 0; 
            background-color: rgba(255, 160, 122, 0.15);
            font-size: 0.7em;           
        }
        
        .footerPdf p {
            margin: 0;            
        }        
        
    </style>
</head>
<body>
<section class="sectionPdf">
    <div class="headerPdf">
        <img class="logoPdf" src="{{ absolute_url(asset('images/logo.webp')) }}" alt="Logo de l'association Regards de Guerre">
    
        <h1>Commande #{{ orderData.order.id }} du {{ orderData.order.orderDateCreationFr }}</h1>
    </div>
    

    <table class="invoiceTable">
        <thead>
            <tr>
                <th>Exposition</th>
                <th>Ticket</th>
                <th>Qté</th>
                <th class="textRight">Prix Unitaire</th>
                <th class="textRight">Prix Total</th>
            </tr>
        </thead>
        <tbody>
            {% for exhibitionDetails in orderData.details %}
                {% for ticketDetails in exhibitionDetails.tickets %}
                    <tr class="product-row">
                        <td>{{ exhibitionDetails.exhibition }}</td>
                        <td>{{ ticketDetails.ticket }}</td>
                        <td class="textRight">{{ ticketDetails.quantity }}</td>
                        <td class="textRight">{{ ticketDetails.price }} €</td>
                        <td class="textRight">{{ (ticketDetails.quantity * ticketDetails.price) }} €</td>
                    </tr>
                {% endfor %}
            {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <td colspan="4" class="textRight strong">Total de la commande :</td>
                <td class="textRight strong">{{ orderData.total }} €</td>
            </tr>
        </tfoot>
    </table>

    <div class="footerPdf">
        <p>Regards de guerre - Association loi 1901</p>
        <p>Rue de la paix - 75000 PARIS</p>
    </div>
</section>
</body>
</html>